### ISSUE TITLE
Default configuration breaks PVR functionality

### ISSUE THREAD

**Issue by dinkypumpkin** [kolonuk/get_iplayer-docker#1]
It is not a good idea to include --force and --overwrite as defaults. It breaks the PVR functionality because those settings force every programme found in PVR search results to be re-downloaded every time the PVR list is processed, regardless of whether or not it has already been downloaded. I think users will find that to be a waste of bandwidth.

**Comment by kolonuk** [comment]
Again, valuable info! didn't think of that... Can pvr not use the force or
overwite, or rather, can those options be set just for the cli/web?

**Comment by dinkypumpkin** [comment]
Web PVR can specify --force separately, but not --overwrite. You have to delete old files from Recordings tab or relocate them from outside Web PVR. Bottom line: keep --force and --overwrite out of your options file since it will be in force if you don't specify those options directly, either in CLI or Web PVR.
