### ISSUE TITLE
Dockerfile installs unnecessary packages

### ISSUE THREAD

**Issue by dinkypumpkin** [kolonuk/get_iplayer-docker#2]
get_iplayer does not use the libxml-perl and libxml-libxml-simple-perl packages. You only need to install libxml-libxml-perl (which is currently pulled in by libxml-libxml-simple-perl). It also doesn't use libcgi-fast-perl. You only need to install libcgi-pm-perl (which is currently pulled in by libcgi-fast-perl). These extra packages are harmless, but unnecessary.

**Comment by kolonuk** [comment]
hi!

Thanks for the feedback! Yes, I know there are some
overlaps/duplicates/unesessary stuff here, but I was kinda in a hurry to
get it setup and working on my new docker setup - old one died with some
horrible docker error and I didn't take a backup! Plus I learnt a lot about
docker creation too!

I'll revisit tonight probably and create a testing branch to play with...

Cheers!

**Comment by kolonuk** [comment]
Fixed in test branch, will merge later

**Comment by dinkypumpkin** [comment]
A few other efficiencies if you want to get carried away:

- JSON::PP is a core Perl module, so there is no need for libjson-pp-perl package
- Your --modes setting is redundant (it is the default)
- You don't need --subtitles with --subs-embed
- You shouldn't use --type or --no-purge with --refresh in the first cron job command line. If you feel you must define those, put them in preferences so users can control those settings separately. Many users couldn't care less about radio programmes.
- You shouldn't use --type or --no-purge with --pvr in the second cron job command line, for the same reason. Additionally, you shouldn't be overriding --type defined in PVR searches. That could produce unwanted downloads from matches not expected by the user. Again, better to put those in preferences if you feel you must define them.
